CREATE DATABASE JOINS;
USE JOINS;


CREATE TABLE STDUENT
(
ID INT PRIMARY KEY,
NAME VARCHAR(20)
);

INSERT INTO STUDENT
VALUES
(101,"ADAM"),
(102,"BOB"),
(103,"CASEY");

SELECT * FROM STUDENT;

CREATE TABLE COURSE
(
ID INT PRIMARY KEY,
COURSE VARCHAR(20)
);

INSERT INTO COURSE (ID,COURSE)
VALUES
(102,"ENGLISH"),
(105,"MATH"),
(103,"SCIENCE"),
(107,"COMPUTER SCIENCE");
# INNER JOIN SHOWS THE COMMON DATA OF TABLE
SELECT *
FROM STUDENT
INNER JOIN COURSE
ON STUDENT.ID = COURSE.ID;

# LEFT JOINS IT GIVES YOU DATA LEFT DATA FULL AND OVERLAP DATA OF RIGHT TABLE 

SELECT *
FROM STUDENT
LEFT JOIN COURSE
ON STUDENT.ID = COURSE.ID;

# RIGHT JOINS IT GIVES YOU DATA RIGHT DATA FULL AND OVERLAP DATA OF LEFT TABLE 

SELECT *
FROM STUDENT
RIGHT JOIN COURSE
ON STUDENT.ID = COURSE.ID;

# FULL JOIN IN MY SQL IS DOESN'T CONSIDER COMMNAD SO WE USE ALTERNATE METHOD
# IT SHOW COMBINE DATA OF BOTH THE TABLE IT DONT SHOW MULTIPLE TIME COMBINE DATE

SELECT *
FROM STUDENT
LEFT JOIN COURSE
ON STUDENT.ID = COURSE.ID
UNION
SELECT *
FROM STUDENT
RIGHT JOIN COURSE
ON STUDENT.ID = COURSE.ID;


# LEFT ECLUSIVE JOIN IT TAKE ONLY DATA IS NOT COMBINING OR OVERLAP TO ANOTHER TABLE

SELECT *
FROM STUDENT AS S
LEFT JOIN COURSE AS C
ON S.ID= C.ID
WHERE C.ID IS NULL;

# RIGHT ECLUSIVE JOIN IT TAKE ONLY DATA IS NOT COMBINING OR OVERLAP TO ANOTHER TABLE

SELECT *
FROM STUDENT AS S
RIGHT JOIN COURSE AS C
ON S.ID= C.ID
WHERE S.ID IS NULL;

# UNION IT GIVES U ALL DATA FROM BOTH THE SET

SELECT NAME FROM STUDENT
UNION
SELECT COURSE FROM COURSE;
